### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by danialkoosha56** [v-i-s-h/LinkIt-One-Linux-Arduino-Support-#3]
dear Vishnu Raj
cuold you send me content of  {/home/vish/.arduino15/packages/LinkItOneLinuxArduino} folder
mediatek does not support linkit one and its SDK
or guide me i can solve my problem
thanks.

**Comment by v-i-s-h** [comment]
Hi @danialkoosha56 , I haven't been using these boards for quite sometime and hence do not have those file in my system. I am sorry that I am not of much help in this issue.
